# Generated by Django 3.1.1 on 2020-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['is_taken', '-pick_up_date'], 'verbose_name': 'Dotacja', 'verbose_name_plural': 'Dotacje'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False, verbose_name='picked up'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken_date',
            field=models.DateField(blank=True, null=True, verbose_name='pick up confirmation date'),
        ),
    ]
