# Generated by Django 3.1.1 on 2020-09-27 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20200925_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_of_submission',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='picked up'),
        ),
    ]
